### PR TITLE
Move GridMenu dev preferences to main preferences

### PR DESCRIPTION
**Pull request by wpride**
See http://manage.dimagi.com/default.asp?220695
cross https://github.com/dimagi/commcare-hq/pull/10683

cc @amstone326 to confirm analytics stuff is moved correctly
cc @amsagoff

### CODE REVIEW

**Comment by wpride** [comment]
Release Note: Can now enable grid menus for entire application

**Comment by amstone326** [comment]
Looks OK to me

**Comment by phillipm** [comment]
:+1:
Are there docs that need to be updated since you are moving this out from under a dev feature flag?
Maybe remove it from [this list](https://confluence.dimagi.com/display/ccinternal/CommCare+Android+Developer+Options#CommCareAndroidDeveloperOptions-GridMenusEnabled) and add it a list explaining the CommCare Settings menu, if that exists.

**Comment by ctsims** [comment]
Creating a case for documentation on this feature.

**Comment by wpride** [comment]
@ctsims thanks

**Pull request merged**
