### PR TITLE
Optional Report Error Button on Home Menu

### PR DESCRIPTION
**Pull request by ctsims**
Potential fix for the awkwardness of only having 3 buttons
device-2015-10-21-122536

### CODE REVIEW

**Comment by phillipm** [comment]
Probably worth running by @amsagoff and @biyeun.
In my opinion, we don't want our app to be crashing enough to warrant a large "report an issue" button on the home screen. Maybe we could change the logout button to be a rectangle at the bottom of the screen similar to https://github.com/dimagi/commcare-odk/pull/599

**Comment by ctsims** [comment]
Hey,

It's basically just there temporarily for Matt et. All to demo the app. The
real end-users don't care about the 3-button layout, really.

-Clayton

**Comment by phillipm** [comment]
Sounds good. They are going to be on a master build, right? So we could merge this after 2.24 is cut, and then have time to come up with a more robust solution.

**Comment by ctsims** [comment]
Yeah, that seems true.

-Clayton

**Comment by biyeun** [comment]
OMG. Did you make that button @phillipm? :heart_eyes:

**Comment by ctsims** [comment]
@biyeun That's a clayton original thank you very much :p

**Comment by amsagoff** [comment]
So just to clarify, this is *not* a product feature? @ctsims ?

**Comment by ctsims** [comment]
Yeah, it's hidden and mostly for people to demo with.

I still think it'd be nice for 2.24 but no strong feelings.

**Comment by biyeun** [comment]
@ctsims are you a secret designer o_O

**Comment by wpride** [comment]
@ctsims good to merge after conflicts resolved

**Comment by phillipm** [comment]
Bump
Should we close this or try to get it into 2.25?

**Comment by phillipm** [comment]
We should use a vector image for this, to prevent high memory usage from drawing the button, just like the other home screen buttons. I can take care of that, just don't merge in the meantime

**Pull request merged**
