### PR TITLE
Fix image resizing bug

### PR DESCRIPTION
**Pull request by wpride**
Fix for http://manage.dimagi.com/default.asp?178867

### CODE REVIEW

**Comment by wpride** [comment]
apparently adjustViewBounds() in a recent API to allow images to upscale to the maximum available space (what we did manually before), so we need to not do this in the default case (non-scale) case

**Comment by phillipm** [comment]
Just tested this on https://www.commcarehq.org/a/ccqa/apps/view/9e0457117893a5337ea7d9e0d70e9256/releases/ and got 
screen
which seems like it is still broken?

**Comment by wpride** [comment]
Did you use 89 (most recent) or 87 (most recent starred)?

**Comment by phillipm** [comment]
Pretty sure it was 87. Is it working for you?

**Comment by wpride** [comment]
Try 89 - on 87 this is set to full resize so is expected behavior

**Comment by phillipm** [comment]
Got it. Looks good!

**Comment by wpride** [comment]
Fix bug with image resizing for form entry media

**Pull request merged**
