### PR TITLE
Grid Icons resolution fix

### PR DESCRIPTION
**Pull request by wpride**
Fix for http://manage.dimagi.com/default.asp?221195

Use a bigger icon when using grid menus

Adding don't pull for now for question: is it SOP to add the icon to every folder? Some subset of them? If so, what are the go-to sizes? (If we even have a policy)

### CODE REVIEW

**Comment by ctsims** [comment]
@wpride One of the two icons should get added (form v. folder) depending on the type if there is no specified icon.

I actually am not sure what the default size "Should" be in this case, since it's so screen size specific. I think roughly 1/3 of the largest supported resolution would be the default box, with probably 30% margins?

**Comment by wpride** [comment]
@ctsims yeah got the form v. folder part, was actually asking about ldpi v mdpi v ldpi v xhdpi - do we usually add an icon to each of these?

**Comment by ctsims** [comment]
Ah, shouldn't need to with Vector Graphics

**Comment by wpride** [comment]
@ctsims thanks, this is gtg then unless there's other feedback

**Pull request merged**
