### PR TITLE
Newui/show CommCare version as Snackbar

### PR DESCRIPTION
**Pull request by dcluna**
Shows the CommCare version as a Snackbar element with an optional button to copy the version to the clipboard.

CommCareActivity now extends AppCompatActivity, and this may cause some unexpected bugs. If this is not acceptable, I'll try another approach.

### CODE REVIEW

**Comment by phillipm** [comment]
I get this error on a 2.3.7 device:
```
DEVICE SHELL COMMAND: pm install -r "/data/local/tmp/org.commcare.dalvik"
pkg: /data/local/tmp/org.commcare.dalvik
Failure [INSTALL_FAILED_MISSING_SHARED_LIBRARY]
```

Install works fine on a 5.1 device

**Comment by dcluna** [comment]
The missing shared library error happens in a physical device or an emulator?

**Comment by phillipm** [comment]
A physical device, though it is running cyanogenmod, so it is entirely possible it is missing some crucial google library. Works fine on a 4.4.2 tablet.

**Comment by phillipm** [comment]
Just checked and it has the same problem on a gingerbread emulator too.

**Comment by phillipm** [comment]
Actually, I'm also getting this error for older devices on master too. It is probably because my emulator wasn't using Google APIs and my old device is cyanogenmod, which probably has similar issues. Did you get it running on a gingerbread emulator?

**Comment by phillipm** [comment]
I think this might introduce more bugs than it is worth. For instance, the app title isn't shown on the Login screen and background colors seem grey in places that they used to be white or black.

**Pull request closed without merging**
