### PR TITLE
Use the latest support libs

### PR DESCRIPTION
**Pull request by phillipm**
Linting build.gradle :)

This will require you to launch your sdk manager and downloaded the corresponding updates, but it shouldn't be a big download.

### CODE REVIEW

**Comment by ctsims** [comment]
@phillipm  - Do we need to update the SDK manager on the build server as well?

**Comment by phillipm** [comment]
oh, right. I'll do that now

**Comment by phillipm** [comment]
@ctsims should be good to go

**Comment by ctsims** [comment]
@phillipm Hey,

this broke on jenkins so I had to revert:

http://jenkins.dimagi.com/job/commcare-odk/407739/

**Pull request merged**
