### PR TITLE
Updated pinned notifications to Android 5 standards

### PR DESCRIPTION
**Pull request by phillipm**
Pinned notifications weren't showing up on devices targeting API 21/22 because the standards changed to require transparency in the notification images.

Updated notification icons to have transparent backgrounds to comply with Android 5 standards. https://developer.android.com/about/versions/android-5.0-changes.html#BehaviorNotifications

Tested on API 10 and API 22 devices

### CODE REVIEW

**Comment by ctsims** [comment]
Looks great! 

Question: Is it clear whether any older devices are gonna look odd with this change?

**Comment by phillipm** [comment]
@ctsims On the API 10 device the icon is a little hard to see because it is a white logo on a silver notification background. Is it worth doing an api version check and drawing a different background on lower APIs?

Just tested on a Android 4 tablet and it looks fine.

**Comment by ctsims** [comment]
should be as easy as moving the old ones to drawable-v10, right?

**Comment by phillipm** [comment]
@ctsims oh, right, good call! I've changed it such that only Android 4 devices and above get the new icons.

**Pull request merged**
