### PR TITLE
Support swipe navigation on case select/detail

### PR DESCRIPTION
**Pull request by orangejenny**
UV ticket: http://dimagi.uservoice.com/forums/194737-commcare-mobile/suggestions/5738905-revamp-select-client-in-odk-case-detail

Changes:
- On case detail, swiping forward on case detail takes you to the next screen and swiping backward takes you back to case select
- On case select, swiping forward does nothing and swiping backward takes you to the previous screen
- On the first screen of a form, swiping backward pops up the save/ignore dialog to exit the form (so that if you inadvertently swipe into a form, you can just as easily back out)
- If there's a case list menu item (display cases without going to forms) and you go to case detail, swiping in either direction takes you back to case select.
- On the double-pane landscape layout that combines entity select & detail, swiping forward will go into the form if you have a case selected and do nothing if you don't have a case selected. Swiping backwards will take you to the previous screen. I can see an argument for swiping backward unselecting the selected case instead, but given that we don't currently have a way to unselect a case, didn't seem necessary to do that.
- Text of case detail button changed from "Select" to "Continue"

@amsagoff fyi, let me know if you don't think these are the right decisions

### CODE REVIEW

**Comment by amsagoff** [comment]
Agree with all your nav decisions. Awesome!

**Comment by orangejenny** [comment]
[4:59:30 PM] Clayton Sims: Q: Is there a reason we woudln't want this to be added to CommCareActivity and have an optional-to-implement method that's just called "onForwardSwipe" that we can implement in each participating activity?
[4:59:41 PM] Clayton Sims: This also interacts acceptably with the tabbed details, right?

**Comment by orangejenny** [comment]
@ctsims Addressed comments, ready for review

**Comment by wpride** [comment]
@orangejenny this is awesome, ready to merge after conflicts resolved

**Comment by orangejenny** [comment]
@wspride thanks! should be good to go now

**Pull request merged**
