### PR TITLE
Track home screen button clicks, preference and settings clicks

### PR DESCRIPTION
**Pull request by wpride**
Some initial UX tracking as requested by @amsagoff

### CODE REVIEW

**Comment by amsagoff** [comment]
hoooolllaaaa

**Comment by ctsims** [comment]
Hey, @amsagoff - This is gonna seriously inflate the logs for a bunch of people I think and I'd like to find a way to put this into a quick alt-logging framework so we send/collect these things a bit more cleanly. Is there a spec/general notion of where this work fits? Aliza's planning and implementing analytics in a more thorough way and I'd rather not keep fragmenting how we collect this stuff.

**Comment by amsagoff** [comment]
Will and I talked about this as an easy win that could produce some
immediately actionable information. If it's going to blow things up in the
existing framework, fine to drop.

**Comment by amstone326** [comment]
@wpride Are you ok with me closing this? Going to be doing all of this in the first pass of google analytics

**Pull request closed without merging**
