### PR TITLE
fix scrollbar overlap in case tiles

### PR DESCRIPTION
**Pull request by wpride**

### CODE REVIEW

**Comment by wpride** [comment]
http://manage.dimagi.com/default.asp?181173

**Comment by ctsims** [comment]
Will:

Is there a way we can make these calculations not dependent on global screen size in general? I don't super love custom casing things like this and it makes a lot of assumptions about screen elements

**Comment by wpride** [comment]
@ctsims maybe we should offline but confused what the alternative would be?

**Comment by ctsims** [comment]
I think the alternative would be either grabbing the parent view size in
the onmeasure phase or making the layout dynamic. Likely the former. We can
chat about how to structure that.

-Clayton

**Comment by wpride** [comment]
@ctsims I've looked around and can't find an obvious solution here, can you suggest something?

**Comment by orangejenny** [comment]
looks all right to me, @ctsims is your comment blocking?

**Comment by ctsims** [comment]
Pulling for now. will address the long-term implications later.

**Pull request merged**
